# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Application.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1366, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 700))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.rit_logo = QtGui.QLabel(self.centralwidget)
        self.rit_logo.setGeometry(QtCore.QRect(-1, -10, 1366, 111))
        self.rit_logo.setObjectName(_fromUtf8("rit_logo"))
        self.project_title = QtGui.QLabel(self.centralwidget)
        self.project_title.setGeometry(QtCore.QRect(0, 110, 1366, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Manjari"))
        self.project_title.setFont(font)
        self.project_title.setObjectName(_fromUtf8("project_title"))
        self.dsp = QtGui.QCheckBox(self.centralwidget)
        self.dsp.setGeometry(QtCore.QRect(570, 170, 64, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Manjari"))
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.dsp.setFont(font)
        self.dsp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dsp.setMouseTracking(False)
        self.dsp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dsp.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dsp.setAcceptDrops(False)
        self.dsp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dsp.setIconSize(QtCore.QSize(0, 0))
        self.dsp.setCheckable(True)
        self.dsp.setChecked(True)
        self.dsp.setAutoExclusive(False)
        self.dsp.setTristate(False)
        self.dsp.setObjectName(_fromUtf8("dsp"))
        self.reset_button_2 = QtGui.QPushButton(self.centralwidget)
        self.reset_button_2.setEnabled(True)
        self.reset_button_2.setGeometry(QtCore.QRect(420, 620, 71, 61))
        self.reset_button_2.setWhatsThis(_fromUtf8(""))
        self.reset_button_2.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/clear_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_button_2.setIcon(icon1)
        self.reset_button_2.setIconSize(QtCore.QSize(25, 25))
        self.reset_button_2.setDefault(False)
        self.reset_button_2.setFlat(False)
        self.reset_button_2.setObjectName(_fromUtf8("reset_button_2"))
        self.listView_2 = QtGui.QListView(self.centralwidget)
        self.listView_2.setEnabled(False)
        self.listView_2.setGeometry(QtCore.QRect(650, 160, 707, 551))
        palette = QtGui.QPalette()
        self.listView_2.setPalette(palette)
        font = QtGui.QFont()
        font.setKerning(True)
        self.listView_2.setFont(font)
        self.listView_2.setMouseTracking(False)
        self.listView_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listView_2.setAutoFillBackground(False)
        self.listView_2.setStyleSheet(_fromUtf8(""))
        self.listView_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listView_2.setFrameShadow(QtGui.QFrame.Raised)
        self.listView_2.setLineWidth(1)
        self.listView_2.setMidLineWidth(0)
        self.listView_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listView_2.setObjectName(_fromUtf8("listView_2"))
        self.syn_button = QtGui.QPushButton(self.centralwidget)
        self.syn_button.setGeometry(QtCore.QRect(500, 340, 131, 61))
        self.syn_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.syn_button.setWhatsThis(_fromUtf8(""))
        self.syn_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/syn_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.syn_button.setIcon(icon2)
        self.syn_button.setIconSize(QtCore.QSize(30, 30))
        self.syn_button.setDefault(True)
        self.syn_button.setFlat(False)
        self.syn_button.setObjectName(_fromUtf8("syn_button"))
        self.kan_input = QtGui.QTextEdit(self.centralwidget)
        self.kan_input.setGeometry(QtCore.QRect(20, 200, 611, 131))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.kan_input.setFont(font)
        self.kan_input.setLocale(QtCore.QLocale(QtCore.QLocale.Kannada, QtCore.QLocale.India))
        self.kan_input.setFrameShape(QtGui.QFrame.StyledPanel)
        self.kan_input.setFrameShadow(QtGui.QFrame.Raised)
        self.kan_input.setObjectName(_fromUtf8("kan_input"))
        self.columnView_2 = QtGui.QColumnView(self.centralwidget)
        self.columnView_2.setGeometry(QtCore.QRect(10, 160, 631, 271))
        self.columnView_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.columnView_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.columnView_2.setObjectName(_fromUtf8("columnView_2"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 170, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 140, 1341, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.en_input = QtGui.QTextEdit(self.centralwidget)
        self.en_input.setGeometry(QtCore.QRect(20, 480, 611, 131))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.en_input.setFont(font)
        self.en_input.setFrameShadow(QtGui.QFrame.Raised)
        self.en_input.setObjectName(_fromUtf8("en_input"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 450, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.translate_button = QtGui.QPushButton(self.centralwidget)
        self.translate_button.setGeometry(QtCore.QRect(500, 620, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.translate_button.setFont(font)
        self.translate_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/translate_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.translate_button.setIcon(icon3)
        self.translate_button.setIconSize(QtCore.QSize(25, 25))
        self.translate_button.setObjectName(_fromUtf8("translate_button"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 590, 160, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.reset_button_1 = QtGui.QPushButton(self.centralwidget)
        self.reset_button_1.setEnabled(True)
        self.reset_button_1.setGeometry(QtCore.QRect(420, 340, 71, 61))
        self.reset_button_1.setWhatsThis(_fromUtf8(""))
        self.reset_button_1.setText(_fromUtf8(""))
        self.reset_button_1.setIcon(icon1)
        self.reset_button_1.setIconSize(QtCore.QSize(25, 25))
        self.reset_button_1.setDefault(False)
        self.reset_button_1.setFlat(False)
        self.reset_button_1.setObjectName(_fromUtf8("reset_button_1"))
        self.previous_button = QtGui.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(1210, 620, 61, 61))
        self.previous_button.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_button.setIcon(icon4)
        self.previous_button.setIconSize(QtCore.QSize(50, 50))
        self.previous_button.setFlat(True)
        self.previous_button.setObjectName(_fromUtf8("previous_button"))
        self.next_button = QtGui.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(1280, 620, 61, 61))
        self.next_button.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_button.setIcon(icon5)
        self.next_button.setIconSize(QtCore.QSize(50, 50))
        self.next_button.setFlat(True)
        self.next_button.setObjectName(_fromUtf8("next_button"))
        self.play_button = QtGui.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(670, 620, 61, 61))
        self.play_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_button.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon6)
        self.play_button.setIconSize(QtCore.QSize(50, 50))
        self.play_button.setFlat(True)
        self.play_button.setObjectName(_fromUtf8("play_button"))
        self.stop_button = QtGui.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(730, 620, 61, 61))
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon7)
        self.stop_button.setIconSize(QtCore.QSize(66, 66))
        self.stop_button.setFlat(True)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.play_progress = QtGui.QSlider(self.centralwidget)
        self.play_progress.setEnabled(False)
        self.play_progress.setGeometry(QtCore.QRect(660, 560, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.play_progress.setFont(font)
        self.play_progress.setMaximum(100)
        self.play_progress.setPageStep(10)
        self.play_progress.setTracking(True)
        self.play_progress.setOrientation(QtCore.Qt.Horizontal)
        self.play_progress.setInvertedAppearance(False)
        self.play_progress.setInvertedControls(False)
        self.play_progress.setTickPosition(QtGui.QSlider.TicksBelow)
        self.play_progress.setTickInterval(10)
        self.play_progress.setObjectName(_fromUtf8("play_progress"))
        self.text_view = QtGui.QTextEdit(self.centralwidget)
        self.text_view.setEnabled(True)
        self.text_view.setGeometry(QtCore.QRect(660, 170, 340, 315))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.text_view.setFont(font)
        self.text_view.setFrameShape(QtGui.QFrame.WinPanel)
        self.text_view.setFrameShadow(QtGui.QFrame.Plain)
        self.text_view.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text_view.setObjectName(_fromUtf8("text_view"))
        self.refresh_button = QtGui.QPushButton(self.centralwidget)
        self.refresh_button.setGeometry(QtCore.QRect(1130, 620, 61, 61))
        self.refresh_button.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/img/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon8)
        self.refresh_button.setIconSize(QtCore.QSize(50, 50))
        self.refresh_button.setFlat(True)
        self.refresh_button.setObjectName(_fromUtf8("refresh_button"))
        self.analysis_button = QtGui.QPushButton(self.centralwidget)
        self.analysis_button.setGeometry(QtCore.QRect(660, 500, 341, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.analysis_button.setFont(font)
        self.analysis_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.analysis_button.setAutoFillBackground(False)
        self.analysis_button.setIconSize(QtCore.QSize(30, 30))
        self.analysis_button.setShortcut(_fromUtf8(""))
        self.analysis_button.setCheckable(False)
        self.analysis_button.setAutoDefault(False)
        self.analysis_button.setDefault(False)
        self.analysis_button.setFlat(False)
        self.analysis_button.setObjectName(_fromUtf8("analysis_button"))
        self.misc_button = QtGui.QPushButton(self.centralwidget)
        self.misc_button.setGeometry(QtCore.QRect(1009, 500, 341, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.misc_button.setFont(font)
        self.misc_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.misc_button.setAutoFillBackground(True)
        self.misc_button.setIconSize(QtCore.QSize(30, 30))
        self.misc_button.setCheckable(False)
        self.misc_button.setAutoDefault(False)
        self.misc_button.setDefault(False)
        self.misc_button.setFlat(False)
        self.misc_button.setObjectName(_fromUtf8("misc_button"))
        self.columnView_3 = QtGui.QColumnView(self.centralwidget)
        self.columnView_3.setGeometry(QtCore.QRect(10, 440, 631, 271))
        self.columnView_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.columnView_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.columnView_3.setObjectName(_fromUtf8("columnView_3"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(665, 540, 681, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(995, 170, 20, 315))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(665, 485, 681, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.details_table = QtGui.QTableWidget(self.centralwidget)
        self.details_table.setGeometry(QtCore.QRect(1010, 171, 340, 315))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_table.sizePolicy().hasHeightForWidth())
        self.details_table.setSizePolicy(sizePolicy)
        self.details_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.details_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.details_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.details_table.setCornerButtonEnabled(False)
        self.details_table.setObjectName(_fromUtf8("details_table"))
        self.details_table.setColumnCount(1)
        self.details_table.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.details_table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.details_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.details_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.details_table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.details_table.setItem(6, 0, item)
        self.details_table.horizontalHeader().setStretchLastSection(True)
        self.details_table.verticalHeader().setStretchLastSection(True)
        self.columnView_3.raise_()
        self.columnView_2.raise_()
        self.listView_2.raise_()
        self.rit_logo.raise_()
        self.project_title.raise_()
        self.dsp.raise_()
        self.reset_button_2.raise_()
        self.syn_button.raise_()
        self.kan_input.raise_()
        self.label_7.raise_()
        self.line.raise_()
        self.en_input.raise_()
        self.label_8.raise_()
        self.translate_button.raise_()
        self.label.raise_()
        self.reset_button_1.raise_()
        self.previous_button.raise_()
        self.next_button.raise_()
        self.play_button.raise_()
        self.stop_button.raise_()
        self.play_progress.raise_()
        self.text_view.raise_()
        self.refresh_button.raise_()
        self.analysis_button.raise_()
        self.misc_button.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.details_table.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuView.setTearOffEnabled(False)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTheme = QtGui.QMenu(self.menubar)
        self.menuTheme.setObjectName(_fromUtf8("menuTheme"))
        self.menuLanguage = QtGui.QMenu(self.menubar)
        self.menuLanguage.setObjectName(_fromUtf8("menuLanguage"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionDevelopers = QtGui.QAction(MainWindow)
        self.actionDevelopers.setObjectName(_fromUtf8("actionDevelopers"))
        self.actionMentor = QtGui.QAction(MainWindow)
        self.actionMentor.setObjectName(_fromUtf8("actionMentor"))
        self.actionAbout_Project = QtGui.QAction(MainWindow)
        self.actionAbout_Project.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout_Project.setObjectName(_fromUtf8("actionAbout_Project"))
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName(_fromUtf8("actionLicense"))
        self.actionSynthesized_Text = QtGui.QAction(MainWindow)
        self.actionSynthesized_Text.setMenuRole(QtGui.QAction.ApplicationSpecificRole)
        self.actionSynthesized_Text.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionSynthesized_Text.setObjectName(_fromUtf8("actionSynthesized_Text"))
        self.actionGTK = QtGui.QAction(MainWindow)
        self.actionGTK.setCheckable(True)
        self.actionGTK.setChecked(True)
        self.actionGTK.setObjectName(_fromUtf8("actionGTK"))
        self.actionWindows = QtGui.QAction(MainWindow)
        self.actionWindows.setCheckable(True)
        self.actionWindows.setObjectName(_fromUtf8("actionWindows"))
        self.actionPlastique = QtGui.QAction(MainWindow)
        self.actionPlastique.setCheckable(True)
        self.actionPlastique.setObjectName(_fromUtf8("actionPlastique"))
        self.actionMotif = QtGui.QAction(MainWindow)
        self.actionMotif.setCheckable(True)
        self.actionMotif.setObjectName(_fromUtf8("actionMotif"))
        self.actionCleanlooks = QtGui.QAction(MainWindow)
        self.actionCleanlooks.setCheckable(True)
        self.actionCleanlooks.setObjectName(_fromUtf8("actionCleanlooks"))
        self.actionCDE = QtGui.QAction(MainWindow)
        self.actionCDE.setCheckable(True)
        self.actionCDE.setObjectName(_fromUtf8("actionCDE"))
        self.actionTranslations_Text = QtGui.QAction(MainWindow)
        self.actionTranslations_Text.setObjectName(_fromUtf8("actionTranslations_Text"))
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setObjectName(_fromUtf8("actionEnglish"))
        self.actionKannada = QtGui.QAction(MainWindow)
        self.actionKannada.setCheckable(True)
        self.actionKannada.setObjectName(_fromUtf8("actionKannada"))
        self.actionReport = QtGui.QAction(MainWindow)
        self.actionReport.setObjectName(_fromUtf8("actionReport"))
        self.menuAbout.addAction(self.actionDevelopers)
        self.menuAbout.addAction(self.actionMentor)
        self.menuAbout.addAction(self.actionLicense)
        self.menuAbout.addAction(self.actionAbout_Project)
        self.menuAbout.addAction(self.actionReport)
        self.menuView.addAction(self.actionSynthesized_Text)
        self.menuView.addAction(self.actionTranslations_Text)
        self.menuTheme.addAction(self.actionGTK)
        self.menuTheme.addAction(self.actionWindows)
        self.menuTheme.addAction(self.actionPlastique)
        self.menuTheme.addAction(self.actionMotif)
        self.menuTheme.addAction(self.actionCleanlooks)
        self.menuTheme.addAction(self.actionCDE)
        self.menuLanguage.addAction(self.actionEnglish)
        self.menuLanguage.addAction(self.actionKannada)
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuTheme.menuAction())
        self.menubar.addAction(self.menuLanguage.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Kannada Speech Synthesis", None))
        MainWindow.setProperty("lang", _translate("MainWindow", "en", None))
        self.rit_logo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/img/img/icon.svg\" width=\"100\" height=\"100\"/></p></body></html>", None))
        self.project_title.setWhatsThis(_translate("MainWindow", "Hello World", None))
        self.project_title.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Manjari\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Kannada Speech Synthesis</span></p></body></html>", None))
        self.dsp.setToolTip(_translate("MainWindow", "Apply Signal Processing Operations", None))
        self.dsp.setText(_translate("MainWindow", "DSP", None))
        self.reset_button_2.setToolTip(_translate("MainWindow", "Clear", None))
        self.reset_button_2.setStatusTip(_translate("MainWindow", "Clear English Text", None))
        self.reset_button_2.setShortcut(_translate("MainWindow", "Ctrl+Del", None))
        self.syn_button.setToolTip(_translate("MainWindow", "Synthesize", None))
        self.syn_button.setStatusTip(_translate("MainWindow", "Synthesize", None))
        self.syn_button.setShortcut(_translate("MainWindow", "Ctrl+Return", None))
        self.label_7.setText(_translate("MainWindow", "Kannada Text", None))
        self.label_8.setText(_translate("MainWindow", "English Text", None))
        self.translate_button.setToolTip(_translate("MainWindow", "Translate (en-kn)", None))
        self.translate_button.setStatusTip(_translate("MainWindow", "Translate", None))
        self.translate_button.setShortcut(_translate("MainWindow", "Alt+Return", None))
        self.label.setText(_translate("MainWindow", "Powered by Google Translate", None))
        self.reset_button_1.setToolTip(_translate("MainWindow", "Clear", None))
        self.reset_button_1.setStatusTip(_translate("MainWindow", "Clear Kannada Text", None))
        self.reset_button_1.setShortcut(_translate("MainWindow", "Ctrl+Del", None))
        self.previous_button.setToolTip(_translate("MainWindow", "Previous", None))
        self.previous_button.setStatusTip(_translate("MainWindow", "Previous", None))
        self.previous_button.setShortcut(_translate("MainWindow", "Alt+Left", None))
        self.next_button.setToolTip(_translate("MainWindow", "Next", None))
        self.next_button.setStatusTip(_translate("MainWindow", "Next", None))
        self.next_button.setShortcut(_translate("MainWindow", "Alt+Right", None))
        self.play_button.setToolTip(_translate("MainWindow", "Play", None))
        self.play_button.setStatusTip(_translate("MainWindow", "Play", None))
        self.play_button.setShortcut(_translate("MainWindow", "Ctrl+Space", None))
        self.stop_button.setToolTip(_translate("MainWindow", "Stop", None))
        self.stop_button.setStatusTip(_translate("MainWindow", "Stop", None))
        self.stop_button.setShortcut(_translate("MainWindow", "Ctrl+Shift+Space", None))
        self.refresh_button.setToolTip(_translate("MainWindow", "Refresh", None))
        self.refresh_button.setStatusTip(_translate("MainWindow", "Refresh", None))
        self.refresh_button.setShortcut(_translate("MainWindow", "F5", None))
        self.analysis_button.setToolTip(_translate("MainWindow", "Audio Analysis", None))
        self.analysis_button.setStatusTip(_translate("MainWindow", "Audio Analysis and Plots", None))
        self.analysis_button.setText(_translate("MainWindow", "Analysis", None))
        self.misc_button.setToolTip(_translate("MainWindow", "Misc. Operations", None))
        self.misc_button.setStatusTip(_translate("MainWindow", "Misc. Operations", None))
        self.misc_button.setText(_translate("MainWindow", "Miscellaneous", None))
        item = self.details_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "DB-ID", None))
        item = self.details_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Name", None))
        item = self.details_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Location", None))
        item = self.details_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Processed", None))
        item = self.details_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "User Rating", None))
        item = self.details_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Duration", None))
        item = self.details_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sampling Rate", None))
        item = self.details_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Total Samples", None))
        item = self.details_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Details", None))
        __sortingEnabled = self.details_table.isSortingEnabled()
        self.details_table.setSortingEnabled(False)
        item = self.details_table.item(6, 0)
        item.setText(_translate("MainWindow", "16 kHz", None))
        self.details_table.setSortingEnabled(__sortingEnabled)
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme", None))
        self.menuLanguage.setTitle(_translate("MainWindow", "Language", None))
        self.actionDevelopers.setText(_translate("MainWindow", "Developers", None))
        self.actionDevelopers.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionMentor.setText(_translate("MainWindow", "Mentor", None))
        self.actionMentor.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.actionAbout_Project.setText(_translate("MainWindow", "About Project", None))
        self.actionAbout_Project.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionLicense.setText(_translate("MainWindow", "License", None))
        self.actionLicense.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.actionSynthesized_Text.setText(_translate("MainWindow", "Synthesis List", None))
        self.actionSynthesized_Text.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.actionGTK.setText(_translate("MainWindow", "GTK", None))
        self.actionGTK.setShortcut(_translate("MainWindow", "Ctrl+1", None))
        self.actionWindows.setText(_translate("MainWindow", "Windows", None))
        self.actionWindows.setShortcut(_translate("MainWindow", "Ctrl+2", None))
        self.actionPlastique.setText(_translate("MainWindow", "Plastique", None))
        self.actionPlastique.setShortcut(_translate("MainWindow", "Ctrl+3", None))
        self.actionMotif.setText(_translate("MainWindow", "Motif", None))
        self.actionMotif.setShortcut(_translate("MainWindow", "Ctrl+4", None))
        self.actionCleanlooks.setText(_translate("MainWindow", "Cleanlooks", None))
        self.actionCleanlooks.setShortcut(_translate("MainWindow", "Ctrl+5", None))
        self.actionCDE.setText(_translate("MainWindow", "CDE", None))
        self.actionCDE.setShortcut(_translate("MainWindow", "Ctrl+6", None))
        self.actionTranslations_Text.setText(_translate("MainWindow", "Translations List", None))
        self.actionTranslations_Text.setShortcut(_translate("MainWindow", "Ctrl+Shift+L", None))
        self.actionEnglish.setText(_translate("MainWindow", "English", None))
        self.actionKannada.setText(_translate("MainWindow", "Kannada", None))
        self.actionReport.setText(_translate("MainWindow", "About this Application", None))

import AppResources_rc
